[package]
name = "fast-pinball-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
serialport = "4.7.2"

[[example]]
name = "neutron_init"
path = "examples/neutron_init.rs"
